/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
        './resources/js/**/*.js',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                primary: {
                    50: '#ECFDF5',
                    100: '#D1FAE5',
                    200: '#A7F3D0',
                    300: '#6EE7B7',
                    400: '#00C1A3',
                    500: '#006B59',
                    600: '#005A4A',
                    700: '#004D3F',
                    800: '#003D32',
                    900: '#002E25',
                },
                'cm-primary': '#006B59',
                'cm-primary-container': '#00C1A3',
                'cm-secondary': '#4A6078',
                'cm-tertiary': '#006B5C',
                'cm-surface': '#FAF8FF',
                'cm-surface-container': '#EAEDFF',
                'cm-surface-container-low': '#F2F3FF',
                'cm-surface-container-high': '#E2E7FF',
                'cm-surface-container-highest': '#DAE2FD',
                'cm-surface-container-lowest': '#FFFFFF',
                'cm-surface-dim': '#D2D9F4',
                'cm-on-surface': '#131B2E',
                'cm-on-background': '#131B2E',
                'cm-on-primary': '#FFFFFF',
                'cm-on-secondary': '#FFFFFF',
                'cm-outline': '#6C7A75',
                'cm-outline-variant': '#BBCAC4',
                'cm-inverse-surface': '#283044',
                'cm-inverse-on-surface': '#EEF0FF',
                'cm-inverse-primary': '#42DDBE',
                'cm-primary-fixed-dim': '#42DDBE',
                'cm-secondary-container': '#CBE2FE',
                'cm-tertiary-container': '#00C1A7',
                'cm-error': '#BA1A1A',
                'cm-error-container': '#FFDAD6',
                'cm-on-surface-variant': '#3C4A45',
                'cm-surface-variant': '#DAE2FD',
                'cm-secondary-fixed-dim': '#B2C9E4',
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
                headline: ['Plus Jakarta Sans', 'Inter', 'system-ui', 'sans-serif'],
            },
            boxShadow: {
                'up': '0 -4px 6px -1px rgba(0, 0, 0, 0.07), 0 -2px 4px -2px rgba(0, 0, 0, 0.05)',
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
    ],
}
