-- ============================================
-- MySQL: Public app no longer needs MySQL access
-- ============================================
-- softyfact-public now uses:
--   - SQLite for blog_posts and contact_leads (local)
--   - HTTP API to fetora-pro for orders (via PUBLIC_SITE_API_KEY)
--
-- This file is kept for reference only.
-- No MySQL user needed for softyfact-public.
-- ============================================
